all:
	g++ -o configparser configparser.cpp
	g++ -o modlistparser modlistparser.cpp
	g++ -o modinfoparser modinfoparser.cpp
debug:
	g++ -o configparser configparser.cpp -g
	g++ -o modlistparser modlistparser.cpp -g
	g++ -o modinfoparser modinfoparser.cpp -g
clean:
	rm configparser modlistparser modinfoparser
cleantemp:
	rm *~
